### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by djbobbydrake** [adgreen93/kpassproj#1]
Hey Alex, thanks for getting this done. Some feedback below:
1. Got a warning message about no repository field when running `npm install`. You may be running an older version. I'm running the latest `3.10.7`. I just went ahead and added the field in the package.json to get things working.
2. Ran `npm install`. Nothing happened. It looks like you've checked in the `node_modules` folder into the repo. This isn't good practice. You just need to add your dependencies to package.json.
3. Got the app running at `localhost:3000` with `node index.js`.
4. Am not seeing the full functionality on my end. Am seeing a js warning in the console:

```
angular.js:12520Error: [$parse:syntax] http://errors.angularjs.org/1.4.8/$parse/syntax?p0=%3A&p1=is%20an%20unexpec…7Blocation.borough.name%7D%7D'&p4=%3A%20'%7B%7Blocation.borough.name%7D%7D'
```

Let me know if I'm doing something wrong.

**Comment by adgreen93** [comment]
Hey Chhay,
Sorry about those errors. You're completely right, its bad practice to have
committed node_modules into the main project. For this project I wanted it all
good to go once you cloned it.
I updated the readme with better instructions, including what port it opens up
to on local host.
And yes - fixed that javascript error as well. Just a bit of errant code in
select box in Column B.
The fixes are on Github now, so you can pull down the changes and it'll be good
to go!

adgreen93/kpassproj

 kpassproj - searching through boroughs, neighborhoods, and macro neighborhoods

 github.com

On Wed, Sep 14, 2016 11:39 AM, Chhay Chhun notifications@github.com
wrote:
Hey Alex, thanks for getting this done. Some feedback below:
1. Got a warning message about no repository field when running npm install.
   You may be running an older version. I'm running the latest 3.10.7. I just
   went ahead and added the field in the package.json to get things working.
2. Ran npm install. Nothing happened. It looks like you've checked in the 
   node_modules  folder into the repo. This isn't good practice. You just need
   to add your dependencies to package.json.
3. Got the app running at localhost:3000  with node index.js.
4. Am not seeing the full functionality on my end. Am seeing a js warning in
   the console:

angular.js:12520Error: [$parse:syntax] http://errors.angularjs.org/1.4.8/$parse/syntax?p0=%3A&p1=is%20an%20unexpec…7Blocation.borough.name%7D%7D'&p4=%3A%20'%7B%7Blocation.borough.name%7D%7D'

Let me know if I'm doing something wrong.
